### ISSUE TITLE
RecyclerViewGridLayout示例小Bug一枚

### ISSUE THREAD

**Issue by CFM880** [evilbinary/TvWidget#1]
在RecyclerViewGridLayout示例中，从item99按上键到item91后直接跳到item84，而不是跳到item87；从item98，item97按上键也是同样的效果。

**Comment by evilbinary** [comment]
这个是RecyclerView 控件的问题，一直是这样的。你可以用gridview，或者你可以重写RecyclerViewGridLayout焦点控制部分。这个我有空搞一搞。

**Comment by CFM880** [comment]
我就是准备学习焦点控制的，我的直播程序在手机上已经运行OK了，就差焦点控制控制(^_^)∠※ ，谢谢了，Launcher就靠你的示例了

**Comment by evilbinary** [comment]
新版本已经解决了
